import type { User } from './types';

export const users: User[] = [
  {
    id: 'alex',
    name: 'Alex',
    avatarId: 'user-alex',
    email: 'alex@synergy.life',
    points: 1250,
    streak: 12,
    achievements: ['First 5k', '30-Day Challenge', 'Morning Lark'],
    fitnessGoals: 'Build muscle and improve cardio',
    experienceLevel: 'Intermediate',
    workoutPlan: {
      week: 1,
      weeklyGoal: 'Establish a consistent routine and focus on compound movements.',
      schedule: [
        {
          day: 'Monday',
          title: 'Upper Body Strength',
          focus: 'Chest, Shoulders, Triceps',
          exercises: [
            { name: 'Bench Press', sets: '4', reps: '6-8', rest: '90s' },
            { name: 'Overhead Press', sets: '3', reps: '8-10', rest: '60s' },
            { name: 'Tricep Dips', sets: '3', reps: '10-12', rest: '60s' },
          ],
        },
        {
          day: 'Wednesday',
          title: 'Lower Body Power',
          focus: 'Quads, Hamstrings, Glutes',
          exercises: [
            { name: 'Squats', sets: '4', reps: '6-8', rest: '90s' },
            { name: 'Romanian Deadlifts', sets: '3', reps: '8-10', rest: '60s' },
            { name: 'Leg Press', sets: '3', reps: '10-12', rest: '60s' },
          ],
        },
        {
          day: 'Friday',
          title: 'Cardio & Core',
          focus: 'Endurance and Stability',
          exercises: [
            { name: 'Running', sets: '1', reps: '30 min', rest: 'N/A' },
            { name: 'Plank', sets: '3', reps: '60s hold', rest: '45s' },
            { name: 'Russian Twists', sets: '3', reps: '15 per side', rest: '45s' },
          ],
        },
      ],
      wellnessSuggestions: [
        'Aim for 8 hours of sleep per night.',
        'Meditate for 10 minutes each morning.',
        'Drink at least 3 liters of water daily.',
      ],
    },
    activityLog: [
      { id: 'log1', date: '2024-07-29', activity: 'Upper Body Strength', duration: 60, intensity: 'High' },
      { id: 'log2', date: '2024-07-28', activity: 'Yoga', duration: 45, intensity: 'Low' },
      { id: 'log3', date: '2024-07-27', activity: 'Rest', duration: 0, intensity: 'Low' },
      { id: 'log4', date: '2024-07-26', activity: 'Lower Body Power', duration: 65, intensity: 'High' },
      { id: 'log5', date: '2024-07-25', activity: 'Swimming', duration: 30, intensity: 'Medium' },
      { id: 'log6', date: '2024-07-24', activity: 'Cardio & Core', duration: 50, intensity: 'Medium' },
      { id: 'log7', date: '2024-07-23', activity: 'Rest', duration: 0, intensity: 'Low' },
    ],
  },
  {
    id: 'jordan',
    name: 'Jordan',
    avatarId: 'user-jordan',
    email: 'jordan@synergy.life',
    points: 850,
    streak: 5,
    achievements: ['First Week Streak', 'Early Riser'],
    fitnessGoals: 'Improve flexibility and reduce stress',
    experienceLevel: 'Beginner',
    workoutPlan: {
      week: 1,
      weeklyGoal: 'Incorporate gentle movement and mindfulness into each day.',
      schedule: [
        { day: 'Monday', title: 'Gentle Yoga', focus: 'Flexibility', exercises: [{ name: 'Yoga Flow', sets: '1', reps: '30 min', rest: 'N/A' }] },
        { day: 'Tuesday', title: 'Mindful Walk', focus: 'Cardio', exercises: [{ name: 'Walking', sets: '1', reps: '20 min', rest: 'N/A' }] },
        { day: 'Wednesday', title: 'Full Body Stretch', focus: 'Mobility', exercises: [{ name: 'Stretching Routine', sets: '1', reps: '15 min', rest: 'N/A' }] },
        { day: 'Thursday', title: 'Mindful Walk', focus: 'Cardio', exercises: [{ name: 'Walking', sets: '1', reps: '20 min', rest: 'N/A' }] },
        { day: 'Friday', title: 'Restorative Yoga', focus: 'Relaxation', exercises: [{ name: 'Yoga Flow', sets: '1', reps: '30 min', rest: 'N/A' }] },
      ],
      wellnessSuggestions: ['Practice deep breathing for 5 minutes twice a day.', 'Keep a gratitude journal.', 'Limit screen time before bed.'],
    },
    activityLog: [
      { id: 'log1', date: '2024-07-29', activity: 'Gentle Yoga', duration: 30, intensity: 'Low' },
      { id: 'log2', date: '2024-07-28', activity: 'Rest', duration: 0, intensity: 'Low' },
      { id: 'log3', date: '2024-07-27', activity: 'Full Body Stretch', duration: 15, intensity: 'Low' },
      { id: 'log4', date: '2024-07-26', activity: 'Mindful Walk', duration: 20, intensity: 'Low' },
    ],
  },
  {
    id: 'casey',
    name: 'Casey',
    avatarId: 'user-casey',
    email: 'casey@synergy.life',
    points: 2300,
    streak: 25,
    achievements: ['Mountain Climber', '50-Workout Milestone', 'Perfect Month'],
    fitnessGoals: 'Train for a marathon',
    experienceLevel: 'Advanced',
    workoutPlan: {
      week: 8,
      weeklyGoal: 'Increase long-run distance and maintain tempo pace.',
      schedule: [
        { day: 'Monday', title: 'Tempo Run', focus: 'Speed Endurance', exercises: [{ name: 'Running', sets: '1', reps: '8 miles at tempo pace', rest: 'N/A' }] },
        { day: 'Tuesday', title: 'Cross-Training', focus: 'Active Recovery', exercises: [{ name: 'Cycling', sets: '1', reps: '45 min', rest: 'N/A' }] },
        { day: 'Wednesday', title: 'Interval Training', focus: 'Speed', exercises: [{ name: 'Hill Sprints', sets: '8', reps: '400m', rest: '2 min' }] },
        { day: 'Thursday', title: 'Strength Training', focus: 'Injury Prevention', exercises: [{ name: 'Full Body Circuit', sets: '3', reps: '12-15', rest: '60s' }] },
        { day: 'Saturday', title: 'Long Run', focus: 'Endurance', exercises: [{ name: 'Running', sets: '1', reps: '16 miles', rest: 'N/A' }] },
      ],
      wellnessSuggestions: ['Incorporate foam rolling after every run.', 'Focus on carb-loading before long runs.', 'Prioritize hydration and electrolytes.'],
    },
    activityLog: [
       { id: 'log1', date: '2024-07-29', activity: 'Tempo Run', duration: 70, intensity: 'High' },
       { id: 'log2', date: '2024-07-28', activity: 'Rest', duration: 0, intensity: 'Low' },
       { id: 'log3', date: '2024-07-27', activity: 'Long Run', duration: 150, intensity: 'Medium' },
       { id: 'log4', date: '2024-07-26', activity: 'Rest', duration: 0, intensity: 'Low' },
       { id: 'log5', date: '2024-07-25', activity: 'Strength Training', duration: 45, intensity: 'Medium' },
    ],
  },
];
